"""
Generates the authorship manifest.

docs/12_manifest.md
"""

import datetime
import hashlib
import io
import json

import screenplain.export.pdf as pdf
import screenplain.parsers.fountain as f
from screenplain.types import Screenplay

from src.clickhouse_client import get_provenance_events, get_keystroke_batches
from src.supabase_client import get_client as get_supabase, get_all_components

def generate_manifest(project_id: str, writer_name: str) -> tuple[dict, bytes]:
    """
    Generates the authorship manifest for a project.

    Returns a tuple of the manifest data as a dict and a PDF bytes.
    """
    supabase = get_supabase()
    provenance_events = get_provenance_events(project_id)
    keystroke_batches = get_keystroke_batches(project_id)

    # §6.1 Summary
    summary = generate_summary(project_id, writer_name, provenance_events)

    # §6.2 Composition record
    composition_record = generate_composition_record(provenance_events, keystroke_batches)

    # §6.3 Chain verification
    chain_verification = verify_chain(project_id, keystroke_batches)

    # §6.4 Insertion log
    insertion_log = generate_insertion_log(provenance_events)

    # §6.5 AI involvement
    ai_involvement = generate_ai_involvement(provenance_events)

    # §6.6 Machine-generated assets
    machine_generated_assets = generate_machine_generated_assets(provenance_events)

    # §6.7 Intent development
    intent_development = generate_intent_development(provenance_events)

    # Assemble the manifest
    manifest = {
        "summary": summary,
        "composition_record": composition_record,
        "chain_verification": chain_verification,
        "insertion_log": insertion_log,
        "ai_involvement": ai_involvement,
        "machine_generated_assets": machine_generated_assets,
        "intent_development": intent_development,
        "verbatim_statement": "This document records how this work was created. It is not legal advice. Registrability is determined solely by the U.S. Copyright Office on a case-by-case basis. Consult an attorney regarding registration."
    }
    
    disclosure_mapping = {
        "Author Created": "Entire text of screenplay, including all dialogue, action, and scene description.",
        "Material Excluded / Limitation of Claim": "For the screenplay alone: nothing to exclude — no AI-generated expression is present. If storyboard frames are included in the deposit, exclude them as machine-generated visual material."
    }

    manifest["disclosure_mapping"] = disclosure_mapping

    fountain_doc = f"Title: Authorship Manifest for {summary['title']}\n"
    fountain_doc += f"Credit: Generated by Artie\n"
    fountain_doc += f"Author: {writer_name}\n"
    fountain_doc += f"Date: {datetime.date.today().isoformat()}\n\n"

    for section_title, section_data in manifest.items():
        fountain_doc += f"# {section_title.replace('_', ' ').title()}\n\n"
        if isinstance(section_data, dict):
            fountain_doc += dict_to_fountain(section_data)
        else:
            fountain_doc += f"{section_data}\n\n"

    script: Screenplay = f.parse(fountain_doc)
    buffer = io.BytesIO()
    pdf.export(script, buffer)
    pdf_bytes = buffer.getvalue()

    return manifest, pdf_bytes

def _calculate_sessions(provenance_events: list[dict]) -> tuple[int, float]:
    if not provenance_events:
        return 0, 0.0

    session_count = 1
    working_time = (provenance_events[-1]["ts_micros"] - provenance_events[0]["ts_micros"]) / 1_000_000
    
    for i in range(1, len(provenance_events)):
        time_delta = (provenance_events[i]["ts_micros"] - provenance_events[i-1]["ts_micros"]) / 1_000_000
        if time_delta > 30 * 60:  # 30 minutes
            session_count += 1
            working_time -= time_delta

    return session_count, working_time

def generate_summary(project_id: str, writer_name: str, provenance_events: list[dict]) -> dict:
    """
    Generates the summary section of the manifest.
    """
    supabase = get_supabase()
    try:
        title_res = supabase.table("bible_slots").select("value").eq("project_id", project_id).eq("slot_id", "S13").execute()
        title = title_res.data[0]["value"] if title_res.data else "Untitled"
    except Exception:
        title = "Untitled"

    if not provenance_events:
        return {
            "title": title,
            "writer_of_record": writer_name,
            "date_range": "N/A",
            "session_count": 0,
            "core_statement": "Artificial intelligence was used in the creation of this work. It supplied no expression. The complete record of what it did supply is attached."
        }

    start_time = datetime.datetime.fromtimestamp(provenance_events[0]["ts_micros"] / 1_000_000)
    end_time = datetime.datetime.fromtimestamp(provenance_events[-1]["ts_micros"] / 1_000_000)
    date_range = f"{start_time.strftime('%Y-%m-%d')} to {end_time.strftime('%Y-%m-%d')}"

    session_count, _ = _calculate_sessions(provenance_events)

    return {
        "title": title,
        "writer_of_record": writer_name,
        "date_range": date_range,
        "session_count": session_count,
        "core_statement": "Artificial intelligence was used in the creation of this work. It supplied no expression. The complete record of what it did supply is attached."
    }

def generate_composition_record(provenance_events: list[dict], keystroke_batches: list[dict]) -> dict:
    total_chars_typed = sum(batch['char_delta'] for batch in keystroke_batches if batch['char_delta'] > 0)
    keystroke_batch_count = len(keystroke_batches)
    session_count, elapsed_working_time = _calculate_sessions(provenance_events)

    components_by_type = {}
    scenes = set()
    for event in provenance_events:
        if event["event_type"] == "COMPONENT_INSERTED":
            payload = json.loads(event["payload"])
            component_type = payload.get("component_type", "unknown").lower()
            components_by_type[component_type] = components_by_type.get(component_type, 0) + 1
        elif event["event_type"] == "SCENE_SAVED":
            if event["scene_id"]:
                scenes.add(event["scene_id"])

    return {
        "total_characters_typed": total_chars_typed,
        "keystroke_batches": keystroke_batch_count,
        "sessions": session_count,
        "elapsed_working_time_seconds": elapsed_working_time,
        "components_by_type": components_by_type,
        "scene_count": len(scenes),
    }

def verify_chain(project_id: str, keystroke_batches: list[dict]) -> dict:
    components = {c["component_id"]: c["content_hash"] for c in get_all_components(project_id)}
    
    batches_by_component = {}
    for batch in keystroke_batches:
        component_id = batch["component_id"]
        if component_id not in batches_by_component:
            batches_by_component[component_id] = []
        batches_by_component[component_id].append(batch)

    results = {}
    for component_id, batches in batches_by_component.items():
        batches.sort(key=lambda b: b["ts_start_micros"])
        
        chain_hash = hashlib.sha256(component_id.encode("utf-8")).hexdigest()
        discontinuities = []
        
        for i, batch in enumerate(batches):
            # The logic for chain hash calculation is not specified, so I am assuming a simple concatenation.
            # This might need to be adjusted based on the actual implementation.
            # Based on docs/12_manifest.md §4, it should be SHA256(chain_hash_n-1 || SHA256(content_after_batch_n))
            # However, `content_after_batch` is not available in the keystroke_batches table.
            # I will assume content_hash in the batch IS the hash of the content after the batch.
            
            new_chain_hash = hashlib.sha256(f"{chain_hash}{batch['content_hash']}".encode("utf-8")).hexdigest()

            # The batch itself doesn't store the expected chain hash, so we can't directly verify it.
            # We can only re-calculate the chain and compare it with the final hash in supabase.
            chain_hash = new_chain_hash

        final_content_hash = components.get(component_id)
        if not final_content_hash:
            results[component_id] = {"status": "ERROR", "reason": "Component not found in Supabase"}
        elif chain_hash != final_content_hash:
            results[component_id] = {"status": "DISCONTINUITY", "reason": f"Final chain hash mismatch. Expected {final_content_hash}, got {chain_hash}"}
        else:
            results[component_id] = {"status": "VERIFIED"}
            
    return results

def generate_insertion_log(provenance_events: list[dict]) -> dict:
    insertions = []
    for event in provenance_events:
        if event["event_type"] == "PASTE":
            payload = json.loads(event["payload"])
            insertions.append({
                "timestamp": datetime.datetime.fromtimestamp(event["ts_micros"] / 1_000_000).isoformat(),
                "origin": payload.get("origin", "UNKNOWN"),
                "character_count": payload.get("char_count", 0),
                "target_component_id": payload.get("target_component_id")
            })
    
    return {
        "insertions": insertions,
        "statement": "The system cannot prove content came from outside, only fail to prove it came from inside. Pastes with an origin of UNKNOWN could not be attributed to content copied from within the application."
    }

def generate_ai_involvement(provenance_events: list[dict]) -> dict:
    models = {
        "Artie": "gemini-3.5-flash",
        "Script Supervisor": "gemini-3.5-flash, gemini-3.8-flash",
        "Director": "gemini-3.5-flash, gemini-3-pro-image"
    }
    agent_activity = {
        "Artie": {},
        "Script Supervisor": {},
        "Director": {}
    }
    library_versions = set()
    payload_audit_failures = []

    for event in provenance_events:
        if event["event_type"].startswith("AGENT_"):
            payload = json.loads(event["payload"])
            agent_name = None
            if event["actor"] == "artie":
                agent_name = "Artie"
            elif event["actor"] == "supervisor":
                agent_name = "Script Supervisor"
            elif event["actor"] == "director":
                agent_name = "Director"

            activity = agent_activity.get(agent_name)
            if activity is not None:
                event_category = event["event_type"].replace("AGENT_", "").lower()
                activity[event_category] = activity.get(event_category, 0) + 1

            if "library_version" in payload:
                library_versions.add(payload["library_version"])
            
            # Payload audit
            for key, value in payload.items():
                if isinstance(value, str) and len(value) > 100: # Heuristic for long prose
                    # Simple check for screenplay-like content
                    if value.isupper() or "INT." in value or "EXT." in value:
                        payload_audit_failures.append({
                            "event_id": event["event_id"],
                            "event_type": event["event_type"],
                            "field": key
                        })

    return {
        "models": models,
        "agent_activity": agent_activity,
        "static_library_versions": list(library_versions),
        "payload_audit": {
            "status": "PASSED" if not payload_audit_failures else "FAILED",
            "failures": payload_audit_failures
        },
        "statement": "No agent supplied screenplay text. This is supported by a payload audit of all agent events."
    }

def generate_machine_generated_assets(provenance_events: list[dict]) -> dict:
    assets = []
    for event in provenance_events:
        if event["event_type"] == "FRAME_GENERATED":
            payload = json.loads(event["payload"])
            assets.append({
                "timestamp": datetime.datetime.fromtimestamp(event["ts_micros"] / 1_000_000).isoformat(),
                "asset_uri": payload.get("asset_uri"),
                "model": payload.get("model"),
                "prompt": "Prompt information not available in this event. See FRAME_PROMPT_CONSTRUCTED event for details.", # TODO: Correlate with FRAME_PROMPT_CONSTRUCTED
            })

    return {
        "assets": assets,
        "statement": "Each asset carries a SynthID watermark applied by Google independently of this system. These are pre-visualization reference, not part of the literary work, and excluded from any claim in the screenplay."
    }

def generate_intent_development(provenance_events: list[dict]) -> dict:
    versions = []
    for event in provenance_events:
        if event["event_type"] == "BIBLE_VERSION_CREATED":
            payload = json.loads(event["payload"])
            versions.append({
                "timestamp": datetime.datetime.fromtimestamp(event["ts_micros"] / 1_000_000).isoformat(),
                "bible_version_id": payload.get("bible_version_id"),
                "changed_slots": payload.get("changed_slots"),
                "change_reason": payload.get("change_reason")
            })
    return {"versions": versions}

def dict_to_fountain(data: dict) -> str:
    fountain_str = ""
    for key, value in data.items():
        key_str = key.replace('_', ' ').title()
        if isinstance(value, dict):
            fountain_str += f"> {key_str}\n\n"
            fountain_str += dict_to_fountain(value)
        elif isinstance(value, list):
            fountain_str += f"> {key_str}\n\n"
            for item in value:
                if isinstance(item, dict):
                    fountain_str += dict_to_fountain(item)
                    fountain_str += "---\n"
                else:
                    fountain_str += f"- {item}\n"
            fountain_str += "\n"
        else:
            fountain_str += f"{key_str}: {value}\n"
    return fountain_str


